metier_user_admin:
    path : /
    defaults: { _controller: AdminBundle:Default:load}

admin_iframeload:
    path: /iframe
    defaults: { _controller: AdminBundle:Default:loadiframe}

checkExist:
    path : /checkExist
    defaults: { _controller: AdminBundle:Ecole:checkExist}

tieradded:
    path : /added
    defaults: { _controller: AdminBundle:Ecole:tieradded}

metier_user_licenceadded:
    path : /licenceadded
    defaults: { _controller: AdminBundle:LicenceDef:licenceadded}

metier_user_affiche:
    path: /affichage/id={id}
    defaults: { _controller: AdminBundle:Default:affichage}

admin_afficheLicence:
    path: /affichageLicence/id={id}
    defaults: { _controller: AdminBundle:LicenceDef:affichageLicence}

metier_user_associated:
    path:  /associated
    defaults: { _controller: AdminBundle:LicenceDef:associated}

supprimer_Licence:
    path:  /suppLicence/{id}
    defaults: {_controller: AdminBundle:Ecole:suppLicence}

loadgestionQCM:
    path:     /gestionQCM/{id}
    defaults: { _controller: AdminBundle:QCM:load, id :ajouter }

Add_QCM:
    path: /addQCM
    defaults: { _controller: AdminBundle:QCM:add }

supprimer_QCM:
    path: /supprimerQCM/rep={rep}&qst={qst}&qcm={qcm}
    defaults: { _controller: AdminBundle:QCM:supprimer }

supprimeretablissement:
    path : /supprimeretab/id={id}
    defaults: { _controller: AdminBundle:Ecole:supprimeretab}

ecoles_assiciated:
    path: /ecolesassociated/id={id}
    defaults: { _controller: AdminBundle:Ecole:ecolesassociated}

creeNewModele:
    path: /creeNewModele
    defaults: { _controller: AdminBundle:Default:creeNewModele}

saveNewModele:
    path: /saveNewModele
    defaults: { _controller: AdminBundle:Default:saveNewModele}

modifieretab:
    path: /modifieretablissement/{id}
    defaults: { _controller: AdminBundle:Ecole:modifier}

etabmodif:
    path: /etabmodif
    defaults: { _controller: AdminBundle:Ecole:etabModif}

supprimerQCM:
    path: /supprimerQCM/nom={nom}
    defaults: { _controller: AdminBundle:QCM:deleteQcm}

activate:
    path: /activate/id={id}
    defaults: { _controller: AdminBundle:Ecole:activate}
