ecole:
    resource: "@EcoleBundle/Resources/config/routing.yml"
    prefix:   /ecole/

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin/

generic:
    resource: "@GenericBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"