ecole_admin:
    path:     /admin/{ecole}
    defaults: { _controller: EcoleBundle:Default:loadAdmin }

admin_iframeload:
    path: /iframe
    defaults: { _controller: AdminBundle:Default:loadiframe}

ecole_admin_affiche:
    path: /affichage/id={id}
    defaults: { _controller: EcoleBundle:Default:affichage}

ecole_admin_afficheUser:
    path: /affichageUser/id={id}
    defaults: { _controller: EcoleBundle:Default:affichageUser}

ecole_admin_afficheLicence:
    path: /affichageLicence/id={id}
    defaults: { _controller: EcoleBundle:Default:affichageLicence}

supprimeretablissement:
    path : /admin/supprimeretab/id={id}
    defaults: { _controller: EcoleBundle:Ecole:supprimeretab}

supprimereUtilisateur:
    path : /admin/supprimeruser/id={id}
    defaults: { _controller: EcoleBundle:User:supprimeruser}

ecole_modifieretab:
    path: /modifieretablissement/{id}
    defaults: { _controller: EcoleBundle:Ecole:modifier}

etabmodif:
    path: /admin/etabmodif
    defaults: { _controller: EcoleBundle:Ecole:etabModif}

userModif:
    path: /userModif
    defaults: { _controller: EcoleBundle:User:userModif}

activate:
    path: /admin/activate/id={id}
    defaults: { _controller: EcoleBundle:Ecole:activate}

expired:
    path: /admin/expired/id={id}
    defaults: { _controller: EcoleBundle:User:expired}

addFormation:
    path: /ajouterFormation
    defaults: { _controller: EcoleBundle:Formation:ajouterFormation}

afficherDoc:
    path: /afficherDocument/{id}
    defaults: { _controller: EcoleBundle:Formation:afficherDocument}

adresses_tier:
    path: /admin/adresse/id={id}
    defaults: { _controller: EcoleBundle:Default:adresses}

ecole_checkExist:
    path : /checkExist
    defaults: { _controller: EcoleBundle:Ecole:checkExist}

ecole_tieradded:
    path : /added
    defaults: { _controller: EcoleBundle:Ecole:tieradded}

supprimerFormation:
    path: /supprimerFormation/id={id}
    defaults: { _controller: EcoleBundle:Formation:deleteFormation}

formation_qcm:
    path: /Formation_qcm/id={id}
    defaults: { _controller: EcoleBundle:Formation:formationQcm}

add_formation_qcm:
    path: /add_formation_qcm/id_formation={idformation}/id_qcm={idqcm}
    defaults: { _controller: EcoleBundle:Formation:formationAddQcm}

remove_formation_qcm:
    path: /remove_formation_qcm/id_formation={idformation}/id_qcm={idqcm}
    defaults: { _controller: EcoleBundle:Formation:formationRemoveQcm}
