ecole_admin:
    path:     /admin/{ecole}
    defaults: { _controller: EcoleBundle:Default:loadAdmin }

admin_iframeload:
    path: /iframe
    defaults: { _controller: AdminBundle:Default:loadiframe}

ecole_admin_affiche:
    path: /affichage/id={id}
    defaults: { _controller: EcoleBundle:Default:affichage}

ecole_admin_afficheUser:
    path: /affichageUser/id={id}
    defaults: { _controller: EcoleBundle:Default:affichageUser}

ecole_admin_afficheLicence:
    path: /affichageLicence/id={id}
    defaults: { _controller: EcoleBundle:Default:affichageLicence}

supprimeretablissement:
    path : /admin/supprimeretab/id={id}
    defaults: { _controller: EcoleBundle:Ecole:supprimeretab}

etabmodif:
    path: /admin/etabmodif
    defaults: { _controller: EcoleBundle:Ecole:etabModif}

activate:
    path: /admin/activate/id={id}
    defaults: { _controller: EcoleBundle:Ecole:activate}

